name: Terragrunt Apply

on:
  push:
    branches:
      - main

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.39.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terragrunt-plan

      - name: Apply Terragrunt plan
        run: |
          # Change to infrastructure directory and apply the plan.out file
          cd infrastructure
          terragrunt apply-all ../plan.out
