name: Terragrunt Apply

on:
  push:
    branches:
      - main

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.39.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v3
        with:
          name: terragrunt-plans

      - name: Find and run Terragrunt apply in all directories
        run: |
          # Find all directories with a *.hcl file and run terragrunt apply
          find infrastructure -type f -name "*.hcl" -execdir sh -c 'terragrunt apply plan.out || { echo "Terragrunt apply failed in $(pwd)"; exit 1; }' \;
