name: Terragrunt Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.39.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      # Debug step: List files before running terragrunt plan
      - name: List files in infrastructure before plan
        run: |
          ls -al infrastructure

      - name: Run Terragrunt plan and generate one plan.out
        run: |
          cd infrastructure
          terragrunt plan-all -out=plan.out  # This generates the plan.out inside the 'infrastructure' directory

      # Debug step: List files after running terragrunt plan to check if plan.out was created
      - name: List files in infrastructure after plan
        run: |
          ls -al infrastructure

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terragrunt-plan
          path: infrastructure/plan.out  # Upload from 'infrastructure' directory
          if-no-files-found: warn
