name: Terragrunt Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.39.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Run Terragrunt plan and generate one plan.out
        run: |
          # Change to the root of your infrastructure, then run Terragrunt plans
          cd infrastructure
          terragrunt plan-all -out=../plan.out  # Save the plan output to the root directory

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terragrunt-plan
          path: plan.out  # Single plan.out in the root
