name: Terragrunt Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.39.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Find and run Terragrunt plans in all directories
        run: |
          # Find all directories with a *.hcl file
          find infrastructure/environments -name *.hcl -execdir terragrunt plan -out plan.out \;

        # The above line searches all directories under infrastructure/environments for terragrunt.hcl files
        # and runs terragrunt plan for each.
